[package]
name = "rpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strip-ansi-escapes = "0.1.1"

[[bin]]
name = "rpt"
path = "main.rs"
